## Windows Terminal Themes
# dark_theme = 'Tango Dark'
# light_theme = 'Solarized Light'

## General
# trackdir = true  # automatically add dirs for `p` use
# git_timeout = 120
# disable_git = false
# use_git = false  # instead of gitstatus subpackage
# read_async = true

## Plugins
# If you want to use it, not if you have it
# watchdog = true
# use_pygit2 = false

## Beta
# multiproc = false
# workers = cpu_count - 1  # int
# workers = 4

## Output
# output = "path_to_log" | literal "buffer" | literal "stdout"  # or nothing for None
# output = "C:\some\path"
# output = "buffer"
# output = "stdout"

## Debug
# timeit = false
# test_status = false
# linear = false
# fallback = true
# let_crash = false
